### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipowar#1]
https://github.com/SistemasTecTlaxiaco/mixtecoin/wiki

**Comment by 22620229Angel** [comment]
Despues de haber revisado hemos concluido con darle una calificacion de 30 ya que cumple con todo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
